language: python
sudo: false
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - PANDAS=0
  - PANDAS=1

env:
  - CC=gcc CXX=g++
  - CC=gcc-5 CXX=g++-5

addons:
  postgresql: "9.4"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5

install:
  - ${CC} --version
  - pip install numpy
  - if [ $PANDAS == "1" ];
        pip install pandas;
        python -c "import pandas;print(pandas.__version__)";
    fi
  - python -c "import numpy;print(numpy.__version__)"
  - pip install -e .[dev]

script:
  - py.test warp_prism
  - flake8 warp_prism

notifications:
  email: false
